# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -Wextra -Werror

# client.c and server.c
CFILE = 200104004043_main.c

# Output files
OUTFILE = MWCp

# Libraries
LIBS = -lrt -lpthread

# Build
build:
	$(CC) $(CFILE) $(LIBS) -o $(OUTFILE)

# Clean
clean:
	rm -f $(OUTFILE)
